name       = "fortime"
version    = "0.6.0"
license    = "BSD 3-Clause License"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2023-2025, Seyed Ali Ghasemi"


[dependencies]
FACE = {git="https://github.com/szaghi/FACE.git"}

[dev-dependencies]
forunittest = {git="https://github.com/gha3mi/forunittest"}

[build]
auto-executables = false
auto-tests       = true
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[preprocess]
[preprocess.cpp]


[[example]]
name       = "example1"
source-dir = "example"
main       = "example1.f90"

[[example]]
name       = "example2"
source-dir = "example"
main       = "example2.f90"

[[example]]
name       = "example3"
source-dir = "example"
main       = "example3.f90"

[[example]]
name       = "example4"
source-dir = "example"
main       = "example4.f90"

[[example]]
name       = "example5"
source-dir = "example"
main       = "example5.f90"

[[example]]
name       = "example6"
source-dir = "example"
main       = "example6.f90"


[extra.ford]
project             = "ForTime"
version             = "0.6.0"
year                = "2023-2025"
project_github      = "https://github.com/gha3mi/fortime"
author              = "Seyed Ali Ghasemi"
email               = "info@gha3mi.com"
github              = "https://github.com/gha3mi"
license             = "BSD 3-Clause"
src_dir             = ["src", "example", "test"]
output_dir          = "doc"
source              = true
incl_src            = true
graph               = true
coloured_edges      = true
search              = true
print_creation_date = true
sort                = "permission-alpha"
display             = ["public", "private", "protected"]


[extra.fortitude.check]
ignore = ["S001", "S061", "C003", "C121"]