ctimer_write – ForTime
ctimer_write Subroutine
Seyed Ali Ghasemi
14 statements
Source File
private impure subroutine ctimer_write(this, file_name)
Writes the CPU time to a file.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(in) :: this
character(len=*), intent(in) :: file_name
Called by
Source Code
   impure subroutine ctimer_write(this, file_name)
      class(timer), intent(in) :: this
      character(*), intent(in) :: file_name
      logical                  :: file_exists
      integer                  :: nunit
      ! Check if the file exists
      inquire(file=file_name, exist=file_exists)
      ! Open the file in appropriate mode
      if (file_exists) then
         open(newunit=nunit, file=file_name, status='old', action='write', position='append')
      else
         open(newunit=nunit, file=file_name, status='new', action='write')
      end if
      ! Write the CPU time to the file
      write(nunit, '(g0)') this%cpu_time
      ! Close the file
      close(nunit)
   end subroutine ctimer_write
Call graph
example4 calls ctimer_write
test17 calls ctimer_write
test18 calls ctimer_write
test5 calls ctimer_write
test6 calls ctimer_write