ctimer_start – ForTime
ctimer_start Subroutine
Seyed Ali Ghasemi
4 statements
Source File
private impure subroutine ctimer_start(this)
Starts the timer by recording the current CPU time value. This value is used to calculate the CPU time later.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
Called by
Source Code
   impure subroutine ctimer_start(this)
      class(timer), intent(inout) :: this
      ! Start the timer
      call cpu_time(this%cpu_start)
   end subroutine ctimer_start
Call graph
example3 calls ctimer_start
example4 calls ctimer_start
test16 calls ctimer_start
test17 calls ctimer_start
test18 calls ctimer_start
test4 calls ctimer_start
test5 calls ctimer_start
test6 calls ctimer_start