dtimer_start – ForTime
dtimer_start Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
4 statements
Source File
private impure subroutine dtimer_start(this)
Starts the timer by recording the current processor clock value. This value is used to calculate the elapsed time later.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
Called by
Source Code
   impure subroutine dtimer_start(this)
      class(timer), intent(inout) :: this
      ! Start the timer
      call date_and_time(values=this%values_start)
   end subroutine dtimer_start
Call graph
example5 calls dtimer_start
example6 calls dtimer_start
test25 calls dtimer_start
test26 calls dtimer_start
test27 calls dtimer_start
test28 calls dtimer_start
test29 calls dtimer_start
test30 calls dtimer_start