dtimer_write – ForTime
dtimer_write Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private impure subroutine dtimer_write(this, file_name)
Writes the elapsed time to a file.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(in) :: this
character(len=*), intent(in) :: file_name
Calls
Called by
Call graph
dtimer_write calls write_to_file
example6 calls dtimer_write
test26 calls dtimer_write
test27 calls dtimer_write
test29 calls dtimer_write
test30 calls dtimer_write