dtimer_stop – ForTime
dtimer_stop Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
23 statements
Source File
private impure subroutine dtimer_stop(this, nloops, message, print, color)
Stops the timer and calculates the elapsed time. Optionally, it can print a message along with the elapsed time.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
integer, intent(in), optional :: nloops
character(len=*), intent(in), optional :: message
logical, intent(in), optional :: print
character(len=*), intent(in), optional :: color
Calls
Called by
Call graph
dtimer_stop calls print_time, to_seconds
print_time calls colorize
example5 calls dtimer_stop
example6 calls dtimer_stop
test25 calls dtimer_stop
test26 calls dtimer_stop
test27 calls dtimer_stop
test28 calls dtimer_stop
test29 calls dtimer_stop
test30 calls dtimer_stop