mtimer_stop – ForTime
mtimer_stop Subroutine
Seyed Ali Ghasemi
28 statements
Source File
private impure subroutine mtimer_stop(this, nloops, message, print)
Stops the timer and calculates the MPI time. Optionally, it can print a message along with the MPI time.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
integer, intent(in), optional :: nloops
character(len=*), intent(in), optional :: message
logical, intent(in), optional :: print
Calls
Called by
Source Code
   impure subroutine mtimer_stop(this, nloops, message, print)
      ! include 'mpif.h'
      class(timer), intent(inout)        :: this
      integer,      intent(in), optional :: nloops
      character(*), intent(in), optional :: message
      character(:), allocatable          :: msg
      logical,      intent(in), optional :: print
      interface
         function mpi_wtime()
            import rk
            real(rk) :: mpi_wtime
         end function mpi_wtime
      end interface
      ! Stop the timer
      this%mpi_end = mpi_wtime()
      ! Calculate the elapsed MPI time
      this%mpi_elapsed = this%mpi_end - this%mpi_start
      ! Convert MPI time to seconds
      if (.not.present(nloops)) this%mpi_time = this%mpi_elapsed
      if (     present(nloops)) this%mpi_time = this%mpi_elapsed / real(nloops, kind=rk)
      ! Print the elapsed time
      if (.not. present(message)) then
         msg = "MPI time:"
      else
         msg = message
      end if
      if (present(print)) then
         if (print) call print_time(this%mpi_time, msg)
      else
         call print_time(this%mpi_time, msg)
      end if
      ! Deallocate the message
      if (allocated(msg)) deallocate(msg)
   end subroutine mtimer_stop
Call graph
mtimer_stop calls print_time
test10 calls mtimer_stop
test11 calls mtimer_stop
test12 calls mtimer_stop
test22 calls mtimer_stop
test23 calls mtimer_stop
test24 calls mtimer_stop