mtimer_start – ForTime
mtimer_start Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private impure subroutine mtimer_start(this)
Starts the timer by recording the current MPI time value. This value is used to calculate the MPI time later.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
Called by
Call graph
test10 calls mtimer_start
test11 calls mtimer_start
test12 calls mtimer_start
test22 calls mtimer_start
test23 calls mtimer_start
test24 calls mtimer_start