otimer_start – ForTime
otimer_start Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private impure subroutine otimer_start(this)
Uses
omp_lib
Starts the timer by recording the current OMP time value. This value is used to calculate the OMP time later.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
Calls
Called by
Call graph
otimer_start calls omp_get_wtime
test19 calls otimer_start
test20 calls otimer_start
test21 calls otimer_start
test7 calls otimer_start
test8 calls otimer_start
test9 calls otimer_start