otimer_write – ForTime
otimer_write Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
8 statements
Source File
private impure subroutine otimer_write(this, file_name)
Uses
omp_lib
Writes the OMP time to a file.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(in) :: this
character(len=*), intent(in) :: file_name
Calls
Called by
Call graph
otimer_write calls write_to_file
test20 calls otimer_write
test21 calls otimer_write
test8 calls otimer_write
test9 calls otimer_write