print_time – ForTime
print_time Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private impure subroutine print_time(time, message, color)
Uses
face
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: time
character(len=*), intent(in) :: message
character(len=*), intent(in), optional :: color
Calls
Called by
Source Code
   impure subroutine print_time(time, message, color)
      use face
      real(rk),     intent(in) :: time
      character(*), intent(in) :: message
      character(*), intent(in), optional :: color
      if (present(color)) then
         print '(A, F16.9, A)', colorize(trim(message), color_fg=trim(color)), time, colorize(" [s]", color_fg=trim(color))
      else
         print '(A, F16.9, A)', colorize(trim(message), color_fg='blue'), time, colorize(" [s]", color_fg='blue')
      end if
   end subroutine print_time
Call graph
print_time calls colorize
ctimer_stop calls print_time
dtimer_stop calls print_time
mtimer_stop calls print_time
otimer_stop calls print_time
timer_stop calls print_time
example1 calls timer_stop
example2 calls timer_stop
example3 calls ctimer_stop
example4 calls ctimer_stop
example5 calls dtimer_stop
example6 calls dtimer_stop
test1 calls timer_stop
test10 calls mtimer_stop
test11 calls mtimer_stop
test12 calls mtimer_stop
test13 calls timer_stop
test14 calls timer_stop
test15 calls timer_stop
test16 calls ctimer_stop
test17 calls ctimer_stop
test18 calls ctimer_stop
test19 calls otimer_stop
test2 calls timer_stop
test20 calls otimer_stop
test21 calls otimer_stop
test22 calls mtimer_stop
test23 calls mtimer_stop
test24 calls mtimer_stop
test25 calls dtimer_stop
test26 calls dtimer_stop
test27 calls dtimer_stop
test28 calls dtimer_stop
test29 calls dtimer_stop
test3 calls timer_stop
test30 calls dtimer_stop
test31 calls timer_stop
test4 calls ctimer_stop
test5 calls ctimer_stop
test6 calls ctimer_stop
test7 calls otimer_stop
test8 calls otimer_stop
test9 calls otimer_stop