timer_start – ForTime
timer_start Subroutine
Seyed Ali Ghasemi
5 statements
Source File
public impure subroutine timer_start(this)
Starts the timer by recording the current processor clock value. This value is used to calculate the elapsed time later.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(inout) :: this
Called by
Source Code
   impure subroutine timer_start(this)
      class(timer), intent(inout) :: this
      ! Get the processor clock rate
      call system_clock(count_rate=this%clock_rate)
      ! Start the timer
      call system_clock(count=this%clock_start)
   end subroutine timer_start
Call graph
example1 calls timer_start
example2 calls timer_start
test1 calls timer_start
test2 calls timer_start
test3 calls timer_start