timer_write – ForTime
timer_write Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private impure subroutine timer_write(this, file_name)
Writes the elapsed time to a file.
Type Bound
timer
Arguments
Type Intent Optional Attributes Name
class(timer), intent(in) :: this
character(len=*), intent(in) :: file_name
Calls
Called by
Call graph
timer_write calls write_to_file
example2 calls timer_write
test14 calls timer_write
test15 calls timer_write
test2 calls timer_write
test3 calls timer_write