to_seconds – ForTime
to_seconds Function
Seyed Ali Ghasemi
5 statements
Source File
private pure function to_seconds(values) result(seconds)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(8) :: values
Return Value real(kind=rk)
Called by
Source Code
   pure function to_seconds(values) result(seconds)
      integer, dimension(8), intent(in) :: values
      real(rk)                          :: seconds
      seconds = real(values(3), rk) * 24.0_rk * 60.0_rk * 60.0_rk + &
                real(values(5), rk) * 60.0_rk * 60.0_rk + &
                real(values(6), rk) * 60.0_rk + &
                real(values(7), rk)
   end function to_seconds
Call graph
dtimer_stop calls to_seconds
example5 calls dtimer_stop
example6 calls dtimer_stop
test25 calls dtimer_stop
test26 calls dtimer_stop
test27 calls dtimer_stop
test28 calls dtimer_stop
test29 calls dtimer_stop
test30 calls dtimer_stop