write_to_file – ForTime
write_to_file Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private impure subroutine write_to_file(time, file_name)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: time
character(len=*), intent(in) :: file_name
Called by
Source Code
   impure subroutine write_to_file(time, file_name)
      real(rk), intent(in)     :: time
      character(*), intent(in) :: file_name
      logical                  :: file_exists
      integer                  :: nunit
      ! Check if the file exists
      inquire(file=file_name, exist=file_exists)
      ! Open the file in appropriate mode
      if (file_exists) then
         open(newunit=nunit, file=file_name, status='old', action='write', position='append')
      else
         open(newunit=nunit, file=file_name, status='new', action='write')
      end if
      ! Write the elapsed time to the file
      write(nunit, '(g0)') time
      ! Close the file
      close(nunit)
   end subroutine write_to_file
Call graph
ctimer_write calls write_to_file
dtimer_write calls write_to_file
mtimer_write calls write_to_file
otimer_write calls write_to_file
timer_write calls write_to_file
example2 calls timer_write
example4 calls ctimer_write
example6 calls dtimer_write
test11 calls mtimer_write
test12 calls mtimer_write
test14 calls timer_write
test15 calls timer_write
test17 calls ctimer_write
test18 calls ctimer_write
test2 calls timer_write
test20 calls otimer_write
test21 calls otimer_write
test23 calls mtimer_write
test24 calls mtimer_write
test26 calls dtimer_write
test27 calls dtimer_write
test29 calls dtimer_write
test3 calls timer_write
test30 calls dtimer_write
test5 calls ctimer_write
test6 calls ctimer_write
test8 calls otimer_write
test9 calls otimer_write