example2 – ForTime
example2 Program
12 statements
Source File
Uses
fortime
Calls
Variables
Type Attributes Name Initial
type(timer) :: t
integer :: nl
integer :: nloops = 3
Source Code
program example2
   use fortime
   implicit none
   type(timer) :: t
   integer :: nl, nloops=3
   call t%timer_start()
    do nl = 1, nloops
        call sleep(1) ! Perform operations ntimes
    end do
   call t%timer_stop(nloops = nloops, message = 'Elapsed time:') ! nloops and message are optional.
   call t%timer_write('example/example2_etimes') ! Optionally, write the elapsed time to a file
end program example2
Call graph
example2 calls timer_start, timer_stop, timer_write