example6 – ForTime
example6 Program
12 statements
Source File
Uses
fortime
Calls
Variables
Type Attributes Name Initial
type(timer) :: t
integer :: nl
integer :: nloops = 3
Source Code
program example6
   use fortime
   implicit none
   type(timer) :: t
   integer :: nl, nloops=3
   call t%dtimer_start()
    do nl = 1, nloops
        call sleep(1) ! Perform operations ntimes
    end do
   call t%dtimer_stop(nloops = nloops, message = 'Elapsed time:', print = .true.) ! nloops, message and print are optional.
   call t%dtimer_write('example/example6_etimes') ! Optionally, write the elapsed time to a file
end program example6
Call graph
example6 calls dtimer_start, dtimer_stop, dtimer_write
dtimer_stop calls print_time, to_seconds