test6 – ForTime
test6 Program
13 statements
Source File
Uses
fortime
kinds
Calls
Variables
Type Attributes Name Initial
type(timer) :: t
integer :: nl
integer :: nloops = 3
Source Code
program test6
   use kinds
   use fortime
   implicit none
   type(timer) :: t
   integer :: nl, nloops=3
   ! CPU time with nloops
   call t%ctimer_start()
   do nl = 1, nloops
      call sleep(1) ! Perform operations ntimes
   end do
   call t%ctimer_stop(message = 'CPU time:')
   call t%ctimer_write('test/test6_ctimes') ! Optionally, write the elapsed time to a file
end program test6
Call graph
test6 calls ctimer_start, ctimer_stop, ctimer_write
ctimer_stop calls print_time