test22 – ForTime
test22 Program
15 statements
Source File
Uses
fortime
forunittest
kinds
Calls
Variables
Type Attributes Name Initial
type(timer) :: t
type(unit_test) :: ut
integer :: ierr
Source Code
program test22
   use kinds
   use fortime
   use forunittest
   implicit none
   type(timer) :: t
   type(unit_test) :: ut
   integer :: ierr
#if defined(USE_MPI)
   ! MPI time
   call mpi_init(ierr)
   call t%mtimer_start()
      call sleep(1) ! Perform operations here
   call t%mtimer_stop(print=.false.)
   call mpi_finalize(ierr)
   call ut%check(res=t%mpi_time, expected=1.0_rk, tol=1.0e-1_rk, msg='test22')
#endif
end program test22
Call graph
test22 calls check, mpi_finalize, mpi_init, mtimer_start, mtimer_stop
mtimer_stop calls print_time