test23 – ForTime
test23 Program
BSD 3-Clause
18 statements
Source File
Uses
fortime
forunittest
Calls
Variables
Type Attributes Name Initial
integer :: ierr
integer :: nl
integer :: nloops = 3
type(timer) :: t
type(unit_test) :: ut
Source Code
program test23
   use fortime, only: timer
   use forunittest, only: unit_test, rk
   implicit none
#if defined(USE_MPI)
   type(timer) :: t
   type(unit_test) :: ut
   integer :: nl, nloops=3
   integer :: ierr
   ! MPI time with nloops
   call mpi_init(ierr)
   call t%mtimer_start()
   do nl = 1, nloops
      call sleep(1) ! Perform operations ntimes
   end do
   call t%mtimer_stop(nloops = nloops, message = 'MPI time:', print=.false.)
   call mpi_finalize(ierr)
   call t%mtimer_write('test/test23_mtimes.txt') ! Optionally, write the elapsed time to a file
   call ut%check(res=t%mpi_time, expected=1.0_rk, tol=1.0e-1_rk, msg='test23')
#endif
end program test23
Call graph
test23 calls check, mpi_finalize, mpi_init, mtimer_start, mtimer_stop, mtimer_write
mtimer_stop calls print_time
mtimer_write calls write_to_file
print_time calls colorize