test25 – ForTime
test25 Program
12 statements
Source File
Uses
forunittest
kinds
fortime
Calls
Variables
Type Attributes Name Initial
type(timer) :: t
type(unit_test) :: ut
Source Code
program test25
   use kinds
   use fortime
   use forunittest
   implicit none
   type(timer) :: t
   type(unit_test) :: ut
   ! Elapsed time
   call t%dtimer_start()
      call sleep(1) ! Perform operations here
   call t%dtimer_stop()
   call ut%check(res=t%elapsed_dtime, expected=1.0_rk, tol=1.0e-1_rk, msg='test25')
end program test25
Call graph
test25 calls check, dtimer_start, dtimer_stop
dtimer_stop calls print_time, to_seconds